// <auto-generated />
namespace Moridge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_missingInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_missingInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201605040853188_User_missingInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
